<template>
<h2>General Information</h2>

    <p>College of Software Engineering, Chongqing University of Posts and Telecommunications (CQUPT), was established in 2002 as the first "demonstration software school" in Chongqing. The software engineering major offered by the college is "national characteristic major", and the characteristic major of big data intelligence in Chongqing undergraduate universities, ranking the first place in the "first-class major" construction (science group) of Chongqing undergraduate universities in 2019. Software Engineering is one of the first batch of first-level master's degree programs in China and a key discipline in Chongqing during the 12th five-year plan period.</p>

    <p>The school has more than 80 full-time teachers. Through continuous development and construction, it has formed a team of full-time and part-time teachers composed of scholars and industry experts with solid professional foundation, innovative spirit and rich practical experience. Now there are more than 2,100 undergraduate and graduate students..</p>

    <p>College actively adapt to the national strategy of reinvigorating China through human resource development and innovation driven development strategy, based on the striking information and advantages of CQUPT, relying on domestic and international famous IT companies, set up the HP software college, HP national institute of engineering practice education center, Microsoft IT industry-university-institute cooperation platform, such as artificial intelligence and big data emerging industries, such as training to the integrated use of the software engineering methods, techniques and tools to analyze and solve the problem of complicated engineering high-level software engineering talents with international vision. In communication software, digital media technology, financial education, software testing and other aspects, the college has distinctive characteristics and outstanding advantages.</p>

    <p>The college has communication software engineering center to build the central and local LABS, software quality assurance and engineering training center in Chongqing, telecommunications value-added business and the terminal software institute, software testing technology research institute, CQUPT software engineering research center and image and multimedia laboratory research and development institutions. For undergraduate and graduate education in software engineering it has provided the good study condition and research and development platform. The college has undertaken more than 50 scientific research projects at various levels, including the national natural science foundation of China, the Ministry of Science and Technology and Chongqing Municipality. It has won a series of awards, including the second prize of national science and technology progress award, the first prize of teaching achievements of Chongqing Municipality and the first prize of science and technology progress award, with outstanding contributions to the young and middle-aged experts and a number of academic teachers.</p>

    <p>Focusing on the cultivation of talents, the college is committed to the construction of disciplines and specialties and the reform of education and teaching. College practice "3 + 1" the direction of the five major categories of culture and points of talent training mode, strengthening the foreign language teaching and international cooperation innovation, to provide "outstanding engineers plan", "software + industry + foreign language", "the talent cultivation plan" 121 project characteristic such as training plan, through the project practice accumulated a year, to strengthen the students practical skills, system to cultivate the students' ability to apply the software engineering. The college's undergraduate and graduate students have achieved fruitful results in participating in international and domestic scientific and technological innovation competitions, and have won more than 100 prizes in science and technology competitions at or above the provincial or ministerial level. Graduates have been favored by the employers and the society, ranking the best in employment quality among CQUPT.</p>



</template>
<style scoped>
@import url("../../styles/content.less");
</style>

