<template>
    <h2>Academic Master degree: 083500 Software Engineering</h2>
    <p>     This discipline is authorized by the Academic Master Degree Committee of the State Council in 2011, and awarded the Master of Engineering degree.</p>
    <p>This subject training objectives: training senior talents with a solid foundation of computer software theory, the system master computer software requirements, software analysis and design, software coding and implementation, software testing and so on the specialized knowledge and methods of software engineering, being familiar with the software life cycle and project management, master of digital media technology, embedded software and communication software and other related domain knowledge, who can be engaged in theoretical research, the software system development, software and application software in the field of theory and technique to solve other disciplines of theoretical research and application development issues.</p>
    <p>Features and advantages of the discipline:</p>
    <p>          1. In the field of software engineering theory and method, we are mainly engaged in the research of software development mode, software code automatic generation, trusted software and software testing, paid attention to industry-university-research cooperation in automobile electronics and software testing, and accumulated a number of distinctive research results.</p>
    <p>    2. In the field of communication software, the discipline is mainly engaged in mobile communication protocol stack software, the next generation of mobile communication, telecom operation management, telecommunications value-added services, mobile terminal software, communications security software, such as the direction of research, relying on the provincial level key laboratory, has complete design, development and testing platform, for our country the third generation mobile communication engineering made outstanding contribution for independent innovation.</p>
    <p>    3. In the field of digital media technology, it is mainly engaged in image processing, machine vision, virtual reality technology, medical imaging, streaming media technology, multimedia processing technology, game software, animation software and other directions of research, obtained a number of distinctive results, is undertaking a series of national projects.</p>
    <p> The main degree and professional courses are: software modeling, software development tools and platform, software architecture, software formalization method, advanced software engineering technology, advanced database system, software quality assurance and testing, software metrics, middleware technology, software engineering discipline frontier technology, computer network security technology, cryptography and network security, machine learning, research of digital image processing, digital media and network intelligence, the operating system kernel and design principles, distributed and parallel computing, big data analysis and processing, etc.</p>
</template>
<style scoped>
@import url("../../styles/content.less");
</style>